syntax = "proto3";

package player.v1;

import "player/v1/color.proto";

service InternalService {
  rpc GetAuthor(GetAuthorRequest) returns (GetAuthorResponse);

  rpc GetAuthors(GetAuthorsRequest) returns (GetAuthorsResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
}

message GetAuthorRequest {
  string account_id = 1;
  reserved 2;
  reserved "ip";
}

message GetAuthorResponse {
  string name = 1;
  reserved 2;
  reserved "tag";
  bool admin = 3;
  NameColor color = 4;
  uint32 streak = 5;
}

message GetAuthorsRequest {
  repeated string account_ids = 1;
}

message GetAuthorsResponse {
  repeated Author authors = 1;
}

message Author {
  string account_id = 1;
  string name = 2;
  bool admin = 3;
  NameColor color = 4;
  uint32 streak = 5;
}
