// What a regenerated map does to the tile ids a server already holds.
//
// A tile id is an index into the coordinates blob, so a regeneration moves every id after the first
// tile added or removed, and the ownership on the server is keyed on those ids. That is what
// map/README.md means by "regenerating renumbers every tile" — but the ids are the only thing that
// moves. A tile's **position** does not, so a tile that survives can be followed from one blob to
// the next, and every player keeps the ground they took.
//
// **The mapping is monotonic, and that is what makes it small enough to ship as SQL.** Both blobs
// are the same lattice in the same generation order, filtered by what each calls land, so the tiles
// in both appear in both in the same relative order. A monotonic mapping is a handful of runs — one
// per stretch of ids that moves by a constant offset — rather than a quarter of a million rows.

/**
 * @param {string[]} before positions, as `keyOf` writes them, in the old blob's tile order
 * @param {string[]} after the same for the new blob
 * @returns {{
 *   runs: {from: number, to: number, span: number}[],
 *   kept: number, removed: number[], added: number,
 * }} runs in **wire ids**, 1-based; `removed` holds the wire ids the new blob has no tile for
 */
export function remap(before, after) {
    const oldIndexOf = new Map()
    for (let i = 0; i < before.length; i++) oldIndexOf.set(before[i], i)

    const runs = []
    const survived = new Set()
    let last = -1
    for (let i = 0; i < after.length; i++) {
        const old = oldIndexOf.get(after[i])
        if (old === undefined) continue
        if (old <= last) {
            throw new Error(
                `the mapping is not monotonic: new tile ${i + 1} came from old ${old + 1}, after ${last + 1}. `
                + "Both blobs must be the same lattice in generation order.",
            )
        }
        last = old
        survived.add(old)

        const open = runs[runs.length - 1]
        if (open && open.from + open.span === old + 1 && open.to + open.span === i + 1) {
            open.span++
            continue
        }
        runs.push({from: old + 1, to: i + 1, span: 1})
    }

    const removed = []
    for (let i = 0; i < before.length; i++) if (!survived.has(i)) removed.push(i + 1)

    return {runs, kept: survived.size, removed, added: after.length - survived.size}
}

/**
 * The runs as the body of a postgres migration: rebuild `tiles` under the new ids, move
 * `ledger_takes`, and drop what is left on tiles the new map does not have.
 *
 * Rebuilt rather than updated in place, because the offsets go both ways — a tile added earlier in
 * the lattice pushes later ids up — so an `UPDATE` would collide with a row it has not moved yet.
 *
 * lib/pq sends a statement with no arguments over the simple query protocol, and postgres runs a
 * multi-statement simple query in an implicit transaction — so the whole file lands or none of it
 * does, and the `ON COMMIT DROP` temp tables go with it.
 *
 * `down` writes the same migration the other way. It is honest about what it cannot give back: the
 * takes deleted on the way up are gone, so a tile the old map had and the new one did not comes back
 * unowned.
 */
export function remapSQL({runs, kept, removed, added, before, after, from, to}, {down = false} = {}) {
    const walked = down
        ? runs.map(({from: f, to: t, span}) => ({from: t, to: f, span}))
        : runs
    const values = walked.map(({from: f, to: t, span}) => `    (${f}, ${t}, ${span})`).join(",\n")
    const lost = down ? added : removed.length
    const gained = down ? removed.length : added

    return `-- Follows every owned tile from ${down ? to : from} to ${down ? from : to}.
--
-- Regenerating the coordinates blob renumbers the tiles: an id is an index into it. The positions do
-- not move, so ${kept} of the ${down ? after : before} tiles are the same ground under a new id,
-- ${gained} come back unowned and ${lost} are gone. Generated by the
-- frontend's \`npm run map:generate\`; see map/README.md.
--
-- tile_remap is the mapping run-length encoded: old ids \`from\` .. \`from + span - 1\` become
-- \`to\` .. \`to + span - 1\`. It is monotonic, because both blobs are the same lattice in the same
-- order, which is what keeps this ${walked.length} rows instead of ${kept}.

CREATE TEMP TABLE tile_remap (from_id integer NOT NULL, to_id integer NOT NULL, span integer NOT NULL)
ON COMMIT DROP;

INSERT INTO tile_remap (from_id, to_id, span) VALUES
${values};

CREATE INDEX ON tile_remap (from_id);

-- Rebuilt rather than updated in place: an id can move up or down, so an UPDATE would collide with a
-- row it has not moved yet. A tile with no run is one the new map does not have, and its row goes.
CREATE TEMP TABLE tiles_remapped ON COMMIT DROP AS
SELECT r.to_id + (t.id - r.from_id) AS id, t.country
FROM tiles t
JOIN tile_remap r ON t.id >= r.from_id AND t.id < r.from_id + r.span;

DELETE FROM tiles;
INSERT INTO tiles (id, country) SELECT id, country FROM tiles_remapped;

-- The ledger's tile is not a key, so it moves in place. A take on a tile the new map does not have
-- is deleted: leaving it would let a revert write to an id that now means other ground.
DELETE FROM ledger_takes t
WHERE NOT EXISTS (
    SELECT 1 FROM tile_remap r WHERE t.tile >= r.from_id AND t.tile < r.from_id + r.span
);

UPDATE ledger_takes t
SET tile = r.to_id + (t.tile - r.from_id)
FROM tile_remap r
WHERE t.tile >= r.from_id AND t.tile < r.from_id + r.span;
`
}
