// Generated by `npm run reactions` — do not edit.
import {Reaction} from "../../gen/grpc/chat/v1/chat_pb.ts";

/** Each reaction's image, from Google's Noto Emoji (Apache 2.0), in the order the picker shows them. */
export const REACTION_IMAGES: ReadonlyMap<Reaction, {url: string, label: string}> = new Map([
    [Reaction.LAUGH, {url: "/static/reactions/laugh-b553c8c7.svg", label: "Laughing"}],
    [Reaction.CLOWN, {url: "/static/reactions/clown-1cae785d.svg", label: "Clown"}],
    [Reaction.SKULL, {url: "/static/reactions/skull-ad67a7ed.svg", label: "Skull"}],
    [Reaction.FIRE, {url: "/static/reactions/fire-dbea451b.svg", label: "Fire"}],
    [Reaction.THUMBS_UP, {url: "/static/reactions/thumbs-up-c30d8e01.svg", label: "Thumbs up"}],
    [Reaction.THUMBS_DOWN, {url: "/static/reactions/thumbs-down-06a70158.svg", label: "Thumbs down"}],
    [Reaction.HEART, {url: "/static/reactions/heart-280a633e.svg", label: "Heart"}],
    [Reaction.CRY, {url: "/static/reactions/cry-b8b08458.svg", label: "Crying"}],
    [Reaction.SCREAM, {url: "/static/reactions/scream-0cdebcbc.svg", label: "Screaming"}],
    [Reaction.COOL, {url: "/static/reactions/cool-98f1d7f1.svg", label: "Cool"}],
    [Reaction.THINK, {url: "/static/reactions/think-b393f008.svg", label: "Thinking"}],
    [Reaction.POOP, {url: "/static/reactions/poop-955782f8.svg", label: "Poop"}],
    [Reaction.PARTY, {url: "/static/reactions/party-4da128d9.svg", label: "Party"}],
    [Reaction.MIND_BLOWN, {url: "/static/reactions/mind-blown-9756b17b.svg", label: "Mind blown"}],
    [Reaction.NERD, {url: "/static/reactions/nerd-ad73b5b7.svg", label: "Nerd"}],
    [Reaction.EARTH, {url: "/static/reactions/earth-873feb50.svg", label: "Earth"}],
])
