syntax = "proto3";

package planet.v1;

import "google/protobuf/timestamp.proto";

message TileTaken {
  string account_id = 1;
  uint32 tile_id = 2;
  string country = 3;
  google.protobuf.Timestamp taken_at = 4;
}

message BombLanded {
  string country = 1;
  uint32 tile_id = 2;
  string ground = 3;
  uint32 cleared = 4;
  google.protobuf.Timestamp landed_at = 5;
}

message Fortified {
  string country = 1;
  uint32 landmass_id = 2;
  uint32 tiles = 3;
  google.protobuf.Timestamp fortified_at = 4;
  string ground = 5;
}
