syntax = "proto3";

package planet.v1;

service InternalService {
  rpc GetTakesByCountry(GetTakesByCountryRequest) returns (GetTakesByCountryResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }

  rpc GetTerritory(GetTerritoryRequest) returns (GetTerritoryResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
}

message GetTakesByCountryRequest {
  string account_id = 1;
}

message GetTakesByCountryResponse {
  repeated CountryTakes taken_for = 1;
  repeated CountryTakes taken_from = 2;
}

message CountryTakes {
  string country_id = 1;
  uint64 tiles = 2;
}

message GetTerritoryRequest {}

message GetTerritoryResponse {
  uint32 tiles = 1;
  repeated Territory territories = 2;
}

message Territory {
  string country_id = 1;
  uint32 tiles = 2;
}
