#!/bin/sh
set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
outdir=${1:?usage: render-env.sh <output-directory>}

EXCLUDE='VPS_HOST VPS_USER VPS_SSH_KEY github_token'

: "${SECRETS_JSON:?SECRETS_JSON is unset — the workflow fills it from toJSON(secrets)}"

backend_yaml="$here/backend.yaml"
caddyfile="$here/caddy/Caddyfile"
compose="$here/docker-compose.yaml"
for f in "$backend_yaml" "$caddyfile" "$compose"; do
	[ -f "$f" ] || { echo "render-env.sh: $f is missing" >&2; exit 1; }
done

backend_names=$(grep -oE 'env://[A-Za-z_][A-Za-z0-9_]*' "$backend_yaml" | sed 's|env://||' | sort -u)
caddy_names=$(grep -oE '\{env\.[A-Za-z_][A-Za-z0-9_]*\}' "$caddyfile" | sed -e 's/{env\.//' -e 's/}//' | sort -u)
compose_names=$(grep -oE '\$\{[A-Za-z_][A-Za-z0-9_]*' "$compose" | sed 's/^\${//' | sort -u)

as_json() { printf '%s\n' "$@" | sed '/^$/d' | jq -R . | jq -sc .; }

multiline=$(printf '%s' "$SECRETS_JSON" | jq -r '
	to_entries | map(select(.value | test("\n"))) | map(.key) | join(" ")
')
for name in $multiline; do
	case " $EXCLUDE " in
		*" $name "*) continue ;;
	esac
	echo "render-env.sh: secret $name spans multiple lines and cannot go in an env file" >&2
	echo "render-env.sh: base64-encode the value, or add it to EXCLUDE if nothing on the box reads it" >&2
	exit 1
done

umask 077
mkdir -p "$outdir"
env_tmp="$outdir/.env.tmp.$$"
caddy_tmp="$outdir/.env.caddy.tmp.$$"
backend_tmp="$outdir/.env.backend.tmp.$$"
trap 'rm -f "$env_tmp" "$caddy_tmp" "$backend_tmp"' EXIT

render_public() {
	echo "# Generated by deploy/vps/render-env.sh from env.public and $1 — do not edit by hand."
	echo
	cat "$here/env.public"
	echo
	printf '%s' "$SECRETS_JSON" | jq -r --argjson keep "$2" '
		to_entries
		| map(select(.key as $k | $keep | index($k)))
		| sort_by(.key)
		| .[]
		| "\(.key)=\(.value)"
	'
}

render_public docker-compose.yaml "$(as_json $compose_names)" >"$env_tmp"
render_public Caddyfile "$(as_json $caddy_names)" >"$caddy_tmp"

{
	echo "# Generated by deploy/vps/render-env.sh — do not edit by hand."
	echo "# One line per env:// anchor in backend.yaml."
	echo
	for name in $backend_names; do
		value=$(printf '%s' "$SECRETS_JSON" | jq -r --arg n "$name" '.[$n] // ""')
		printf '%s=%s\n' "$name" "$value"
	done
} >"$backend_tmp"

count_keys() { grep -c '^[^#][^=]*=.' "$1" 2>/dev/null || true; }
public=$(count_keys "$here/env.public")
rendered=$(( $(count_keys "$env_tmp") + $(count_keys "$caddy_tmp") - 2 * public + $(count_keys "$backend_tmp") ))
if [ "$rendered" -le 0 ]; then
	echo "render-env.sh: no secrets rendered — is SECRETS_JSON really toJSON(secrets)?" >&2
	exit 1
fi

mv "$env_tmp" "$outdir/.env"
mv "$caddy_tmp" "$outdir/.env.caddy"
mv "$backend_tmp" "$outdir/.env.backend"
trap - EXIT
echo "render-env.sh: wrote .env, .env.caddy and .env.backend ($rendered secret lines, $public public settings)"
