#!/bin/sh
# Renders the two env files the droplet's stack loads, into the directory given
# as the first argument:
#
#   .env          the public settings in env.public, plus the secrets the
#                 Caddyfile names as {env.NAME}. Caddy loads it.
#   .env.backend  the secrets backend.yaml anchors as env://NAME. The backend
#                 loads it.
#
# Two files rather than one because env_file is all-or-nothing: a container that
# loads a file gets everything in it, so a single .env would hand the TLS proxy
# the secret that mints click sessions.
#
# Nothing here names a secret, and neither does docker-compose.yaml. Each
# service's own config file declares what it needs, and a secret reaches a
# container exactly when that file references it — so adding one is done in the
# GitHub UI plus the one line that uses it, and there is no list to keep in step.
#
# Secrets arrive as one JSON object in SECRETS_JSON, which the workflow fills
# from toJSON(secrets) — Actions secrets cannot be read any other way, so this
# has to run inside a workflow run. Locally it renders whatever SECRETS_JSON
# holds, which is what makes it testable without a real value in sight.
set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
outdir=${1:?usage: render-env.sh <output-directory>}

# Deploy secrets, which no service config references and which therefore already
# reach no file. Named only so the multi-line check below stays quiet about the
# ssh key, which is legitimately multi-line.
EXCLUDE='VPS_HOST VPS_USER VPS_SSH_KEY github_token'

: "${SECRETS_JSON:?SECRETS_JSON is unset — the workflow fills it from toJSON(secrets)}"

backend_yaml="$here/backend.yaml"
caddyfile="$here/Caddyfile"
for f in "$backend_yaml" "$caddyfile"; do
	[ -f "$f" ] || { echo "render-env.sh: $f is missing" >&2; exit 1; }
done

# What each service asks for, read out of the file that asks for it.
backend_names=$(grep -oE 'env://[A-Za-z_][A-Za-z0-9_]*' "$backend_yaml" | sed 's|env://||' | sort -u)
caddy_names=$(grep -oE '\{env\.[A-Za-z_][A-Za-z0-9_]*\}' "$caddyfile" | sed -e 's/{env\.//' -e 's/}//' | sort -u)

# Caddy's file carries what the Caddyfile names and nothing else — not even the
# backend's, which is the whole point of there being two.
keep=$(printf '%s\n' $caddy_names | sed '/^$/d' | jq -R . | jq -sc .)

# A value spanning lines cannot be written as KEY=value: whatever loads the file
# would read the first line as the secret and try to parse the rest as further
# settings. Refuse it by name instead of truncating it into something that looks
# like it worked.
multiline=$(printf '%s' "$SECRETS_JSON" | jq -r '
	to_entries | map(select(.value | test("\n"))) | map(.key) | join(" ")
')
for name in $multiline; do
	case " $EXCLUDE " in
		*" $name "*) continue ;;
	esac
	echo "render-env.sh: secret $name spans multiple lines and cannot go in an env file" >&2
	echo "render-env.sh: base64-encode the value, or add it to EXCLUDE if nothing on the box reads it" >&2
	exit 1
done

umask 077
env_tmp="$outdir/.env.tmp.$$"
backend_tmp="$outdir/.env.backend.tmp.$$"
trap 'rm -f "$env_tmp" "$backend_tmp"' EXIT

# ------------------------------------------------------------------- Caddy's
{
	echo "# Generated by deploy/vps/render-env.sh — do not edit by hand."
	echo "# The next deploy overwrites it. Public settings come from env.public;"
	echo "# the secrets are the ones the Caddyfile names as {env.NAME}."
	echo
	cat "$here/env.public"
	echo
	printf '%s' "$SECRETS_JSON" | jq -r --argjson keep "$keep" '
		to_entries
		| map(select(.key as $k | $keep | index($k)))
		| sort_by(.key)
		| .[]
		| "\(.key)=\(.value)"
	'
} >"$env_tmp"

# ----------------------------------------------------------------- backend's
{
	echo "# Generated by deploy/vps/render-env.sh — do not edit by hand."
	echo "# One line per env:// anchor in backend.yaml."
	echo
	for name in $backend_names; do
		# Written even when unset, because an anchor the loader cannot resolve
		# refuses the boot: an empty value is a setting, a missing one is a fault,
		# and only the config itself knows which of those is allowed here.
		value=$(printf '%s' "$SECRETS_JSON" | jq -r --arg n "$name" '.[$n] // ""')
		printf '%s=%s\n' "$name" "$value"
	done
} >"$backend_tmp"

# An empty or malformed SECRETS_JSON parses to no entries at all, which renders
# two files that are valid, complete-looking and carry not one secret. Cheaper to
# notice here than after they have replaced the files that worked.
# Non-empty assignments only: .env.backend carries a line per anchor whether or
# not the secret is set, so counting lines would never reach zero.
count_keys() { grep -c '^[^#][^=]*=.' "$1" 2>/dev/null || true; }
public=$(count_keys "$here/env.public")
rendered=$(( $(count_keys "$env_tmp") - public + $(count_keys "$backend_tmp") ))
if [ "$rendered" -le 0 ]; then
	echo "render-env.sh: no secrets rendered — is SECRETS_JSON really toJSON(secrets)?" >&2
	exit 1
fi

mv "$env_tmp" "$outdir/.env"
mv "$backend_tmp" "$outdir/.env.backend"
trap - EXIT
echo "render-env.sh: wrote .env and .env.backend ($rendered secrets, $public public settings)"
