// Generated by scripts/writeAtlas.ts — do not edit by hand.
// Regenerate with `npm run atlas`.

/** Content-addressed URL of the flag sprite atlas. */
export const ATLAS_URL = "/static/countries/atlas-f6d58744.png"

/** Pixel size of that image; the display shader needs it to resolve regions. */
export const ATLAS_SIZE = {width: 1300, height: 1232} as const
