// Generated by scripts/writeCoordinates.ts — do not edit by hand.
// Regenerate with `npm run map:generate` (both blobs) or `npm run map` (re-copy the shared one).

export const BORDERS_URL = "/static/borders-67e352b1.bin"
