// Generated by scripts/writeCoordinates.ts — do not edit by hand.
// Regenerate with `npm run coordinates` or `npm run coordinates:convert`.

export const COORDINATES_URL = "/static/coordinates-26a9aeab.bin"
