// Generated by scripts/writeCoordinates.ts — do not edit by hand.
// Regenerate with `npm run map:generate` (both blobs) or `npm run map` (re-copy the shared one).

export const COORDINATES_URL = "/static/coordinates-9998a414.bin"
