// Generated by scripts/writeCoordinates.ts — do not edit by hand.
// Regenerate with `npm run coordinates`, `npm run coordinates:convert` or `npm run map`.

export const COORDINATES_URL = "/static/coordinates-26a9aeab.bin"
