import {createHash} from "node:crypto"
import {mkdirSync, readdirSync, unlinkSync, writeFileSync} from "node:fs"
import {dirname, join, resolve} from "node:path"
import {fileURLToPath} from "node:url"

const frontendRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")

const atlasDir = join(frontendRoot, "static", "countries")
const assetModulePath = join(frontendRoot, "src", "app", "viewer", "atlasAsset.ts")
const atlasNamePattern = /^atlas-[0-9a-f]{8}\.png$/

export function writeAtlas(image: Buffer, coordinates: unknown): {
    fileName: string
    width: number
    height: number
} {
    const {width, height} = readPngSize(image)
    const hash = createHash("sha256").update(image).digest("hex").slice(0, 8)
    const fileName = `atlas-${hash}.png`

    mkdirSync(atlasDir, {recursive: true})
    for (const entry of readdirSync(atlasDir)) {
        if (atlasNamePattern.test(entry) && entry !== fileName) {
            unlinkSync(join(atlasDir, entry))
        }
    }

    writeFileSync(join(atlasDir, fileName), image)
    writeFileSync(join(atlasDir, "atlas.json"), JSON.stringify(coordinates, null, 2))
    writeFileSync(assetModulePath, assetModule(fileName, width, height))

    return {fileName, width, height}
}

export function readPngSize(image: Buffer): {width: number, height: number} {
    const signature = "\x89PNG\r\n\x1a\n"
    if (image.subarray(0, 8).toString("binary") !== signature) {
        throw new Error("atlas image is not a PNG")
    }
    return {width: image.readUInt32BE(16), height: image.readUInt32BE(20)}
}

function assetModule(fileName: string, width: number, height: number): string {
    return `// Generated by scripts/writeAtlas.ts — do not edit by hand.
// Regenerate with \`npm run atlas\`.

export const ATLAS_URL = "/static/countries/${fileName}"

export const ATLAS_SIZE = {width: ${width}, height: ${height}} as const
`
}
