import {createHash} from "node:crypto"
import {copyFileSync, mkdirSync, readdirSync, unlinkSync, writeFileSync} from "node:fs"
import {dirname, join, resolve} from "node:path"
import {fileURLToPath} from "node:url"

import {type Coordinates, encodeCoordinates} from "../src/app/viewer/coordinatesBinary.ts"

const frontendRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = resolve(frontendRoot, "..", "..")

// Both blobs are shared with the backend, so /map is the source of truth and static/ is this app's
// generated copy — the same split as /proto. The backend copies them with its own `make map`.
export const mapDir = join(repoRoot, "map")

export const staticDir = join(frontendRoot, "static")

const viewerDir = join(frontendRoot, "src", "app", "viewer")
const coordinatesPattern = /^coordinates-[0-9a-f]{8}\.bin$/
const bordersPattern = /^borders-[0-9a-f]{8}\.bin$/

export function writeCoordinatesBinary(coordinates: Coordinates): {
    fileName: string
    byteLength: number
    tiles: number
} {
    const buffer = encodeCoordinates(coordinates)
    const bytes = Buffer.from(buffer)
    const hash = createHash("sha256").update(bytes).digest("hex").slice(0, 8)
    const fileName = `coordinates-${hash}.bin`

    sweep(mapDir, coordinatesPattern, fileName)
    writeFileSync(join(mapDir, fileName), bytes)

    syncCoordinatesFromMap()

    return {fileName, byteLength: bytes.byteLength, tiles: coordinates.length}
}

// Copies the shared blob into static/ and points the asset module at it. Separate from the
// generator so a blob changed at the root reaches this app without recomputing it.
export function syncCoordinatesFromMap(): string {
    const fileName = sharedBlobName(coordinatesPattern)

    sweep(staticDir, coordinatesPattern, fileName)
    copyFileSync(join(mapDir, fileName), join(staticDir, fileName))
    writeFileSync(join(viewerDir, "coordinatesAsset.ts"), assetModule("COORDINATES_URL", fileName))

    return fileName
}

// The borders blob has no encoder in src/ to share — the app only decodes it — so the generator
// encodes it and these only say where it goes and sweep what it replaces.
export function bordersPath(fileName: string): string {
    sweep(mapDir, bordersPattern, fileName)
    return join(mapDir, fileName)
}

export function staticBordersPath(fileName: string): string {
    sweep(staticDir, bordersPattern, fileName)
    return join(staticDir, fileName)
}

export function writeBordersAsset(fileName: string): void {
    writeFileSync(join(viewerDir, "bordersAsset.ts"), assetModule("BORDERS_URL", fileName))
}

function sharedBlobName(pattern: RegExp): string {
    const names = readdirSync(mapDir).filter((entry) => pattern.test(entry))
    if (names.length !== 1) {
        throw new Error(`expected one ${mapDir}/${pattern.source}, found ${names.length}`)
    }
    return names[0]
}

// The name is the content hash, so the previous one is stale rather than an alternative.
function sweep(directory: string, pattern: RegExp, keep: string): void {
    mkdirSync(directory, {recursive: true})
    for (const entry of readdirSync(directory)) {
        if (pattern.test(entry) && entry !== keep) {
            unlinkSync(join(directory, entry))
        }
    }
}

function assetModule(name: string, fileName: string): string {
    return `// Generated by scripts/writeCoordinates.ts — do not edit by hand.
// Regenerate with \`npm run map:generate\` (both blobs) or \`npm run map\` (re-copy the shared one).

export const ${name} = "/static/${fileName}"
`
}
