import {createHash} from "node:crypto"
import {copyFileSync, mkdirSync, readdirSync, unlinkSync, writeFileSync} from "node:fs"
import {dirname, join, resolve} from "node:path"
import {fileURLToPath} from "node:url"

import {type Coordinates, encodeCoordinates} from "../src/app/viewer/coordinatesBinary.ts"

const frontendRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = resolve(frontendRoot, "..", "..")

// The blob is shared with the backend, so /map is the source of truth and static/ is this app's
// generated copy — the same split as /proto. The backend copies it with its own `make map`.
export const mapDir = join(repoRoot, "map")

export const staticDir = join(frontendRoot, "static")
export const jsonPath = join(staticDir, "coordinates.json")

const assetModulePath = join(frontendRoot, "src", "app", "viewer", "coordinatesAsset.ts")
const binaryNamePattern = /^coordinates-[0-9a-f]{8}\.bin$/

export function writeCoordinatesBinary(coordinates: Coordinates): {
    fileName: string
    byteLength: number
    tiles: number
} {
    const buffer = encodeCoordinates(coordinates)
    const bytes = Buffer.from(buffer)
    const hash = createHash("sha256").update(bytes).digest("hex").slice(0, 8)
    const fileName = `coordinates-${hash}.bin`

    sweep(mapDir, fileName)
    writeFileSync(join(mapDir, fileName), bytes)

    syncCoordinatesFromMap()

    return {fileName, byteLength: bytes.byteLength, tiles: coordinates.length}
}

// Copies the shared blob into static/ and points the asset module at it. Separate from the
// generator so a blob changed at the root reaches this app without recomputing it.
export function syncCoordinatesFromMap(): string {
    const fileName = sharedBlobName()

    sweep(staticDir, fileName)
    copyFileSync(join(mapDir, fileName), join(staticDir, fileName))
    writeFileSync(assetModulePath, assetModule(fileName))

    return fileName
}

function sharedBlobName(): string {
    const names = readdirSync(mapDir).filter((entry) => binaryNamePattern.test(entry))
    if (names.length !== 1) {
        throw new Error(`expected one ${mapDir}/coordinates-<hash>.bin, found ${names.length}`)
    }
    return names[0]
}

// The name is the content hash, so the previous one is stale rather than an alternative.
function sweep(directory: string, keep: string): void {
    mkdirSync(directory, {recursive: true})
    for (const entry of readdirSync(directory)) {
        if (binaryNamePattern.test(entry) && entry !== keep) {
            unlinkSync(join(directory, entry))
        }
    }
}

function assetModule(fileName: string): string {
    return `// Generated by scripts/writeCoordinates.ts — do not edit by hand.
// Regenerate with \`npm run coordinates\`, \`npm run coordinates:convert\` or \`npm run map\`.

export const COORDINATES_URL = "/static/${fileName}"
`
}
