import {createHash} from "node:crypto"
import {mkdirSync, readdirSync, unlinkSync, writeFileSync} from "node:fs"
import {dirname, join, resolve} from "node:path"
import {fileURLToPath} from "node:url"

const frontendRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")

const atlasDir = join(frontendRoot, "static", "countries")
const assetModulePath = join(frontendRoot, "src", "app", "viewer", "atlasAsset.ts")
const atlasNamePattern = /^atlas-[0-9a-f]{8}\.png$/

/**
 * Writes `static/countries/atlas-<hash>.png` and points `atlasAsset.ts` at it.
 *
 * Same reasoning as the coordinates blob: `public/_headers` caches `/static/*`
 * for a week, so a regenerated atlas under a stable name is served stale. The
 * old workaround was a `?ts=${Date.now()}` on the URL, which made every visit
 * a cache miss and re-downloaded 419 kB of flags that had not changed.
 *
 * The image size ships with the URL because the shader needs it to resolve the
 * sprite regions, and it used to be a hardcoded pair of numbers with a TODO.
 */
export function writeAtlas(image: Buffer, coordinates: unknown): {
    fileName: string
    width: number
    height: number
} {
    const {width, height} = readPngSize(image)
    const hash = createHash("sha256").update(image).digest("hex").slice(0, 8)
    const fileName = `atlas-${hash}.png`

    mkdirSync(atlasDir, {recursive: true})
    for (const entry of readdirSync(atlasDir)) {
        if (atlasNamePattern.test(entry) && entry !== fileName) {
            unlinkSync(join(atlasDir, entry))
        }
    }

    writeFileSync(join(atlasDir, fileName), image)
    writeFileSync(join(atlasDir, "atlas.json"), JSON.stringify(coordinates, null, 2))
    writeFileSync(assetModulePath, assetModule(fileName, width, height))

    return {fileName, width, height}
}

/** Width and height are big-endian uint32s in the PNG's IHDR chunk. */
export function readPngSize(image: Buffer): {width: number, height: number} {
    const signature = "\x89PNG\r\n\x1a\n"
    if (image.subarray(0, 8).toString("binary") !== signature) {
        throw new Error("atlas image is not a PNG")
    }
    return {width: image.readUInt32BE(16), height: image.readUInt32BE(20)}
}

function assetModule(fileName: string, width: number, height: number): string {
    return `// Generated by scripts/writeAtlas.ts — do not edit by hand.
// Regenerate with \`npm run atlas\`.

/** Content-addressed URL of the flag sprite atlas. */
export const ATLAS_URL = "/static/countries/${fileName}"

/** Pixel size of that image; the display shader needs it to resolve regions. */
export const ATLAS_SIZE = {width: ${width}, height: ${height}} as const
`
}
