import {createHash} from "node:crypto"
import {mkdirSync, readdirSync, unlinkSync, writeFileSync} from "node:fs"
import {dirname, join, resolve} from "node:path"
import {fileURLToPath} from "node:url"

import {type Coordinates, encodeCoordinates} from "../src/app/viewer/coordinatesBinary.ts"

const frontendRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")

export const staticDir = join(frontendRoot, "static")
export const jsonPath = join(staticDir, "coordinates.json")

const assetModulePath = join(frontendRoot, "src", "app", "viewer", "coordinatesAsset.ts")
const binaryNamePattern = /^coordinates-[0-9a-f]{8}\.bin$/

/**
 * Writes `static/coordinates-<hash>.bin` and points `coordinatesAsset.ts` at it.
 *
 * The file name carries a content hash because `public/_headers` caches
 * `/static/*` for a week: a regenerated map under a stable name would be served
 * stale, while a new name is simply a cache miss. Stale hashes are deleted so
 * only the current map ships.
 */
export function writeCoordinatesBinary(coordinates: Coordinates): {
    fileName: string
    byteLength: number
    tiles: number
} {
    const buffer = encodeCoordinates(coordinates)
    const bytes = Buffer.from(buffer)
    const hash = createHash("sha256").update(bytes).digest("hex").slice(0, 8)
    const fileName = `coordinates-${hash}.bin`

    mkdirSync(staticDir, {recursive: true})
    for (const entry of readdirSync(staticDir)) {
        if (binaryNamePattern.test(entry) && entry !== fileName) {
            unlinkSync(join(staticDir, entry))
        }
    }

    writeFileSync(join(staticDir, fileName), bytes)
    writeFileSync(assetModulePath, assetModule(fileName))

    return {fileName, byteLength: bytes.byteLength, tiles: coordinates.length}
}

function assetModule(fileName: string): string {
    return `// Generated by scripts/writeCoordinates.ts — do not edit by hand.
// Regenerate with \`npm run coordinates\` or \`npm run coordinates:convert\`.

/** Content-addressed URL of the tile coordinates blob, fetched by points.ts. */
export const COORDINATES_URL = "/static/${fileName}"
`
}
