syntax = "proto3";

package auth.v1;

service InternalService {
  rpc GetVerifyingKey(GetVerifyingKeyRequest) returns (GetVerifyingKeyResponse);
  rpc GetAccount(GetAccountRequest) returns (GetAccountResponse);

  rpc GetCreationDates(GetCreationDatesRequest) returns (GetCreationDatesResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
}

message GetVerifyingKeyRequest {}

message GetVerifyingKeyResponse {
  string public_key = 1;
}

message GetAccountRequest {
  string account_id = 1;
}

message GetAccountResponse {
  bool linked = 1;
  int64 created_at_unix_ms = 2;
}

message GetCreationDatesRequest {
  repeated string account_ids = 1;
}

message GetCreationDatesResponse {
  repeated CreationDate dates = 1;
}

message CreationDate {
  string account_id = 1;
  int64 created_at_unix_ms = 2;
}
